### PR TITLE
Relax versions of dependencies

### LINKED ISSUE #500: Relaxed versions?
## Expected Behavior
`^` is used to specify versions of dependencies

## Current Behavior
Specific versions are used:
```
prop-types "15.7.2"
redux "4.0.1"                                                                                      
reselect "4.0.0"
```

## Possible Solution
Start using `^` in the `package.json` file

### PR DESCRIPTION
**Pull request by daveisfera**
## Description
Use `^` instead of a fixed version (and regenerate `yarn.lock` just for good measure)
Fixes #500 

## Motivation and Context
Allows users of this module to use a version that is more recent and that minimizes the number of installed modules

## How Has This Been Tested?
N/A

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by wcjordan** [comment]
Thanks!  Merging and this will go out w/ our v1.1 release

**Comment by dave-nm** [comment]
Any ETA on when that will be?

**Comment by daveisfera** [comment]
Any ETA on when that will be?

**Comment by wcjordan** [comment]
We don't have a set timeline yet, but I'm guessing we can do a release of this sometime in the next couple weeks.  @pradeepnschrodinger do you have any concerns with that?  Anything we should follow through on before then?

**Comment by pradeepnschrodinger** [comment]
No concerns, but I think I'll just test this locally through LD and make sure nothing weird comes up. We should then be good to go.

**Comment by wcjordan** [comment]
Just a quick update.  We noticed a small issue which blocks the v1.1 release.  Once we have that worked out we'll release.  Apologies for the delays.

**Comment by wcjordan** [comment]
This is now released w/ v1.1.

**Pull request merged**
