### PR TITLE
Add width to FDTCellGroupWrapper

### PR DESCRIPTION
**Pull request by quixotically**
## Description
Add width to FDTCellGroupWrapper in order to enable overflow styling on it.

## Motivation and Context
CellGroupWrappers can now be styled to prevent overflow into other cell groups.

## How Has This Been Tested?
Manually tested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by wcjordan** [comment]
lgtm, but I'm not sure about whether there's any risk w/ backwards compatibility.  Did you get a chance to discuss with Kam whether this should be a patch or a minor

**Comment by KamranAsif** [comment]
Yeah the biggest worry would be backwards compatibility. 
Can we test some common use cases with fixed columns and scrollable cells? A jsfiddle would be great to make sure nothing breaks.

**Comment by quixotically** [comment]
Kam - what specifically did you have in mind? I'm not sure I understand what you're asking. If I understand correctly, the site examples seem to provide what you're asking for, if you minimize the window.

**Comment by KamranAsif** [comment]
@quixotically I am just worried that this will be in some edge cases related to fixed columns or resizing.
Can you build the site on your fork so we can play around with this? 
You'll need to update some scripts in build_helpers before running "npm run publish-site"

**Pull request merged**
