### PR TITLE
Added support to fix columns to the right side of the table.

### PR DESCRIPTION
**Pull request by garytang8**
## Description
Allow columns to be fixed to the right side of the table. This will enable a new `fixedRight` prop on the `Column` components. I have also added a new example for a table with columns fixed to the right.

## Motivation and Context
This will resolve this issue: https://github.com/schrodinger/fixed-data-table-2/issues/121

## How Has This Been Tested?

I created a new example with two columns set to have `fixedRight` to be true and it rendered as expected. I also checked out the other examples and they appear to render correctly as well. In addition to this, I executed `npm run test` and all tests passed.

## Screenshots (if appropriate):
screenshot-fixed-right-columns

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by garytang8** [comment]
@wcjordan I would update the documentation for the ColumnAPI to reflect the new prop, but noticed that the 'docs/api' folder is ignored. Is there a more appropriate way to change the docs?

**Comment by wcjordan** [comment]
The docs are autogenerated, so you should add the prop to FixedDataTableColumn.js and it will update to appear in the documentation.

This looks good from my end, I'll try it out some and merge this weekend.

**Comment by garytang8** [comment]
Nice! That reminded me to add in the prop type. So I guess I can check off the documentation task now. Thanks for looking at this!

**Comment by wcjordan** [comment]
Great, I'll merge and cut a release.  Thanks so much for the PR!

**Pull request merged**
