### PR TITLE
Check old state while resizing

### PR DESCRIPTION
**Pull request by Jamjarman**
Check oldState.isColumnResizing when calculatingState so that this state is not lost if the data is actively updating.

## Description

Add a check of oldState.isColumnResizing if the current state is not resizing.

## Motivation and Context

#268 Fixes this issue.

## How Has This Been Tested?

Updated this code in our project and then attempted to resize columns while updating data.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by wcjordan** [comment]
Did you test this out and did it solve your issue?  If so I'll merge & release shortly

**Comment by Jamjarman** [comment]
Yep, I tested in our codebase and it resolved our issue. I will say that the resizing seemed less smooth than normal but it does work.

**Comment by wcjordan** [comment]
I suspect you may have been running React in dev mode?  It's notoriously slower in that mode & may account for the loss of smoothness you saw.

**Comment by Jamjarman** [comment]
Ah yep that's probably it. Thanks much for your help on this!

**Pull request merged**
